# print('Nilai ordinal dari karakter c adalah',ord('c'))
# print('Nilai ordinal dari karakter a adalah',ord('a'))
# print('Nilai ordinal dari karakter r adalah',ord('r'))
# print('Nilai ordinal dari karakter i adalah',ord('i'))
print('Nilai ordinal dari karakter . adalah',ord('!'))
print('Nilai ordinal dari karakter ; adalah',ord(';'))